# some more ls aliases
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias em='emacs -nw'
alias dd='dd status=progress'
alias _='sudo'
alias c='clear'
alias q='exit'
alias sl='ls'
alias p='uptime -p'
alias d='du -hs'
alias u='sudo apt-get update'
alias ug='sudo apt-get upgrade'
